# send slack messages on job results
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-job-result-notifier
  namespace: <namespce>

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: <namespce>
  name: kubernetes-job-result-notifier-read-jobs
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-job-result-notifier
  namespace: <namespce>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-job-result-notifier-read-jobs
subjects:
  - kind: ServiceAccount
    name: kubernetes-job-result-notifier
    namespace: <namespce>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-job-result-notifier
  name: kubernetes-job-result-notifier
  namespace: <namespce>
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-job-result-notifier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-job-result-notifier
    spec:
      serviceAccountName: kubernetes-job-result-notifier
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/........"
            - name: SEND_MESSAGE_ON_JOB_SUCCESS
              value: "True"
              # list of slack userids, click on a profile, from the kebab menu select "Copy Member ID"
            - name: SLACK_USERS_TO_NOTIFY
              value: '["<userid1>","<userid2","<userid3>"]'
          image: ghcr.io/zanderhavgaard/kubernetes-job-result-notifier:0.1.1
          name: kubernetes-job-result-notifier
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
