# simple job that will fail, for testing
apiVersion: batch/v1
kind: Job
metadata:
  name: job-will-fail-test
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: example
          image: python
          command: # The jobs fails as there is at least one failed index
            # (all even indexes fail in here), yet all indexes
            # are executed as maxFailedIndexes is not exceeded.
            - python3
            - -c
            - |
              import os, sys
              print("Hello world")
              sys.exit(1)
