---
name: publish-container-image

on:
  push:
    branches:
      - "main"

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(poetry version -s)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: zanderhavgaard
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/zanderhavgaard/kubernetes-job-result-notifier:release
            ghcr.io/zanderhavgaard/kubernetes-job-result-notifier:${{ env.VERSION }}
